command_line:
  - sensor:
      name: Jellyfin Media Size
      unit_of_measurement: GB
      unique_id: jellyfin_media_size
      scan_interval: 300
      device_class: data_size
      command: 'test -d /share/USBMEDIABACKUP_Share/ && du -sm /share/USBMEDIABACKUP_Share/ | awk ''{print $1}'' || echo "0"'
      value_template: "{{ (value|int(0) / 1024) | round(3) }}"

  - sensor:
      name: Frigate Folder Size
      unit_of_measurement: GB
      unique_id: frigate_folder_size
      scan_interval: 300
      device_class: data_size
      command: 'test -d /media/frigate/ && du -sm /media/frigate/ | awk ''{print $1}'' || echo "0"'
      value_template: "{{ (value|int(0) / 1024) | round(3) }}"

  - sensor:
      name: M5C Cam Folder Size
      unit_of_measurement: GB
      unique_id: m5ccam_folder_size
      scan_interval: 300
      device_class: data_size
      command: 'test -d /media/m5ccam/ && du -sm /media/m5ccam/ | awk ''{print $1}'' || echo "0"'
      value_template: "{{ (value|int(0) / 1024) | round(3) }}"

  - sensor:
      name: Time Machine Folder Size
      unit_of_measurement: GB
      unique_id: time_machine_folder_size
      scan_interval: 300
      device_class: data_size
      command: 'test -d /media/timemachine/ && du -sm /media/timemachine/ | awk ''{print $1}'' || echo "0"'
      value_template: "{{ (value|int(0) / 1024) | round(3) }}"
      
  - sensor:
      name: Time Machine Backup Folder Size
      unit_of_measurement: GB
      unique_id: time_machine_backup_folder_size
      scan_interval: 300
      device_class: data_size
      command: 'test -d /share/NAS_Share/Timemachine/ && du -sm /media/timemachine/ | awk ''{print $1}'' || echo "0"'
      value_template: "{{ (value|int(0) / 1024) | round(3) }}"