homeassistant:
  customize:
    sensor.sum_charged_to_zoe:
      state_class: total_increasing
    sensor.sum_charged_to_id_4:
      state_class: total_increasing
    sensor.sum_charged_to_cars:
      state_class: total_increasing
    sensor.sum_charged_to_mg4:
      state_class: total_increasing
    sensor.solar_production_today:
      state_class: total_increasing
    sensor.solar_production_total:
      state_class: total_increasing
    sensor.scb_energy_pv_day:
      state_class: total_increasing
    sensor.statistical_range_daily_money_generated_solar:
      state_class: total
      