multiscrape:
  - name: NVME SSD
    resource_template: "http://{{states('sensor.local_ip')|default('192.168.2.205', true)}}:8080/api/device/fxs500pro234920229/details"
    scan_interval: 300
    headers:
      Content-Type: application/json
      User-Agent: REST
    method: GET
    button:
      - name: 'Refresh NVME SSD'
        unique_id: refresh_nvme_ssd
    binary_sensor:
      - unique_id: nvme_ssd_status
        name: NVME SSD Status
        device_class: problem
        value_template: "{{ value_json.data.device.device_status | default(false) | bool }}"
        attributes:
          - name: "Model Name"
            value_template: "{{ value_json.data.device.model_name | default('unavailable', true) }}"
          - name: "Device Name"
            value_template: "{{ value_json.data.device.device_name | default('unavailable', true) }}"
          - name: "Serial Number"
            value_template: "{{ value_json.data.device.serial_number | default('unavailable', true) }}"
          - name: "Updated At"
            value_template: "{{ value_json.data.device.UpdatedAt | default('unavailable', true) }}"
          - name: "Device Status"
            value_template: "{{ value_json.data.device.device_status | default('unavailable') }}"
          - name: "Capacity"
            value_template: >-
              {{ value_json.data.device.capacity | filesizeformat
                 if value_json.data.device.capacity is defined else 'unavailable' }}
          - name: "Temperature"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].temp | default('unavailable', true) if s|length > 0 else 'unavailable' }}
          - name: "Power on Hours"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].power_on_hours | default('unavailable', true) if s|length > 0 else 'unavailable' }}
          - name: "Power Cycle Count"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].power_cycle_count | default('unavailable', true) if s|length > 0 else 'unavailable' }}

  - name: Cudy LT700 Scraper
    resource: http://192.168.10.1/cgi-bin/luci/admin/network/gcom/status?detail=1&iface=4g
    scan_interval: 60
    
    form_submit:
      submit_once: True
      resource: http://192.168.10.1/cgi-bin/luci/
      select: "form"
      input:
        luci_username: admin
        luci_password: !secret router_password
        
    sensor:
      - unique_id: cudy_lte_rsrp
        name: "Cudy RSRP"
        select: "td:has(p:contains('RSRP')) + td p.hidden-xs"
        unit_of_measurement: "dBm"
        device_class: signal_strength
        state_class: measurement
        icon: mdi:signal-cellular-3
        attributes:
          - name: RSRQ
            select: "td:has(p:contains('RSRQ')) + td p.hidden-xs"
            # Einheit wird hier via Template angehängt, da unit_of_measurement hier verboten ist
            value_template: "{{ value | trim }} dB"
          - name: SINR
            select: "td:has(p:contains('SINR')) + td p.hidden-xs"
            value_template: "{{ value | trim }} dB"
          - name: PCC_Band
            select: "td:has(p:contains('PCC')) + td p.hidden-xs"
            value_template: "{{ value | replace('\n', '') | replace(' ', '') | replace('/', ' / ') }}"
          - name: SCC_Band
            select: "td:has(p:contains('SCC')) + td p.hidden-xs"
            value_template: "{{ value | replace('\n', '') | replace(' ', '') | replace('/', ' / ') }}"
          - name: ISP
            select: "td:has(p:contains('Netzwerktyp')) + td p.hidden-xs"
            value_template: "{{ value | trim }}"
            
            
