multiscrape:
  - name: NVME SSD
    resource_template: "http://{{states('sensor.local_ip')|default('192.168.2.205', true)}}:8080/api/device/fxs500pro234920229/details"
    scan_interval: 300
    headers:
      Content-Type: application/json
      User-Agent: REST
    method: GET
    button:
      - name: 'Refresh NVME SSD'
        unique_id: refresh_nvme_ssd
    binary_sensor:
      - unique_id: nvme_ssd_status
        name: NVME SSD Status
        device_class: problem
        value_template: "{{ value_json.data.device.device_status | default(false) | bool }}"
        attributes:
          - name: "Model Name"
            value_template: "{{ value_json.data.device.model_name | default('unavailable', true) }}"
          - name: "Device Name"
            value_template: "{{ value_json.data.device.device_name | default('unavailable', true) }}"
          - name: "Serial Number"
            value_template: "{{ value_json.data.device.serial_number | default('unavailable', true) }}"
          - name: "Updated At"
            value_template: "{{ value_json.data.device.UpdatedAt | default('unavailable', true) }}"
          - name: "Device Status"
            value_template: "{{ value_json.data.device.device_status | default('unavailable') }}"
          - name: "Capacity"
            value_template: >-
              {{ value_json.data.device.capacity | filesizeformat
                 if value_json.data.device.capacity is defined else 'unavailable' }}
          - name: "Temperature"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].temp | default('unavailable', true) if s|length > 0 else 'unavailable' }}
          - name: "Power on Hours"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].power_on_hours | default('unavailable', true) if s|length > 0 else 'unavailable' }}
          - name: "Power Cycle Count"
            value_template: >-
              {% set s = value_json.data.smart_results | default([]) %}
              {{ s[0].power_cycle_count | default('unavailable', true) if s|length > 0 else 'unavailable' }}