multiscrape:
  - name: NVME SSD
    resource: "http://192.168.2.205:8080/api/device/fxs500pro234920229/details"
    scan_interval: 300
    headers:
      Content-Type: application/json
      User-Agent: REST
    method: GET
    button:
      - name: 'Refresh NVME SSD'
        unique_id: refresh_nvme_ssd
    binary_sensor:
      - unique_id: nvme_ssd_status
        name: NVME SSD Status
        device_class: problem
        value_template: "{{ value_json.data.device.device_status | default(false, true) | bool }}"
        attributes:          
          - name: "Model Name"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.model_name if sr|length>0 and sr.model_name is defined else 'unavailable') }}
          - name: "Device Name"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.device_name if sr|length>0 and sr.device_name is defined else 'unavailable') }}
          - name: "Serial Number"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.serial_number if sr|length>0 and sr.serial_number is defined else 'unavailable') }}
          - name: "Updated At"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.UpdatedAt if sr|length>0 and sr.UpdatedAt is defined else 'unavailable') }}
          - name: "Device Status"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.device_status if sr|length>0 and sr.device_status is defined else 'unavailable') }}
          - name: "Capacity"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ ((sr.capacity|filesizeformat) if sr|length>0 and sr.capacity is defined else 'unavailable') }}
          - name: "Temperature"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].temp if sr is iterable and sr|length>0 and sr[0].temp is defined else 'unavailable') }}
          - name: "Power on Hours"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].power_on_hours if sr is iterable and sr|length>0 and sr[0].power_on_hours is defined else 'unavailable') }}
          - name: "Power Cycle Count"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].power_cycle_count if sr is iterable and sr|length>0 and sr[0].power_cycle_count is defined else 'unavailable') }}
            
  - name: SATA SSD
    resource: "http://192.168.2.205:8080/api/device/0x5000000000002b6f/details"
    scan_interval: 300
    headers:
      Content-Type: application/json
      User-Agent: REST
    method: GET
    button:
      - name: 'Refresh SATA SSD'
        unique_id: refresh_sata_ssd
    binary_sensor:
      - unique_id: sata_ssd_status
        name: SATA SSD Status
        device_class: problem
        value_template: "{{ value_json.data.device.device_status | default(false, true) | bool }}"
        attributes:          
          - name: "Model Name"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.model_name if sr|length>0 and sr.model_name is defined else 'unavailable') }}
          - name: "Device Name"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.device_name if sr|length>0 and sr.device_name is defined else 'unavailable') }}
          - name: "Serial Number"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.serial_number if sr|length>0 and sr.serial_number is defined else 'unavailable') }}
          - name: "Updated At"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.UpdatedAt if sr|length>0 and sr.UpdatedAt is defined else 'unavailable') }}
          - name: "Device Status"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ (sr.device_status if sr|length>0 and sr.device_status is defined else 'unavailable') }}
          - name: "Capacity"
            value_template: >-
              {% set sr = value_json.data.device | default({}, true) %}
              {{ ((sr.capacity|filesizeformat) if sr|length>0 and sr.capacity is defined else 'unavailable') }}
          - name: "Temperature"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].temp if sr is iterable and sr|length>0 and sr[0].temp is defined else 'unavailable') }}
          - name: "Power on Hours"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].power_on_hours if sr is iterable and sr|length>0 and sr[0].power_on_hours is defined else 'unavailable') }}
          - name: "Power Cycle Count"
            value_template: >-
              {% set sr = value_json.data.smart_results | default([], true) %}
              {{ (sr[0].power_cycle_count if sr is iterable and sr|length>0 and sr[0].power_cycle_count is defined else 'unavailable') }}