notify:
  - platform: group
    name: "Duncan"
    services:
      - action: mobile_app_poco_f7
      - action: mobile_app_mi_9t

  - platform: group
    name: "Admin"
    services:
      - action: mobile_app_poco_f7
      - action: mobile_app_stephan_iphone

  - platform: group
    name: "Familie"
    services:
      - action: mobile_app_poco_f7
      - action: mobile_app_fp4
      - action: mobile_app_iphone_von_enya
      - action: mobile_app_stephan_iphone