template:
  - select:
      - name: Smart Home Status
        unique_id: smart_home_status
        optimistic: true
        options: "{{ ['Daily', 'Power Save'] }}"
        select_option:
          - choose:
              - conditions: "{{ option == 'Power Save' }}"
                sequence:
                  - action: homeassistant.turn_off
                    target:
                      label_id: optional_off_power_save
                  - action: notify.duncan
                    data:
                      title: Power Save Mode ON
                      message: Smart Home in Power Save Mode
              - conditions: "{{ option == 'Daily' }}"
                sequence:
                  - action: homeassistant.turn_on
                    target:
                      label_id: optional_off_power_save
                  - action: notify.duncan
                    data:
                      title: Power Save Mode OFF
                      message: Smart Home in Daily Mode
                      