sensor:
  # Tasmota newest Version
  - platform: rest
    scan_interval: 43200
    name: Tasmota - newest version
    unique_id: tasmota_newest_version
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    value_template: "{{ value_json.tag_name | replace('v','' ) }}"
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
      Authorization: !secret github_api_authorization
    json_attributes:
      - body

  # OpenBeken newest Version
  - platform: rest
    scan_interval: 43200
    name: OpenBK7231T App - newest version
    unique_id: openbk7231t_app_newest_version
    resource: https://api.github.com/repos/openshwprojects/OpenBK7231T_App/releases/latest
    value_template: "{{ value_json.tag_name | replace('v','' ) }}"
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
      Authorization: !secret github_api_authorization
    json_attributes:
      - body