shell_command:
  mirror_timemachine_to_nas: "./nas_mirror.sh"
  call_timelapse_script: "./Ffmpeg_timeplase.sh '{{output_filename}}'"
  delete_files_webcam1: 'rm -f /media/m5ccam/pictures/*.jpg'
  delete_old_hourly_backups_disk: "find /share/NAS_Share/Backup/ -name 'HourlyBackup*.tar' -type f -mtime +3 -print -delete"
  delete_old_daily_backups_disk: "find /share/NAS_Share/Backup/ -name 'DailyBackup*.tar' -type f -mtime +7 -print -delete"
  delete_old_weekly_backups_disk: "find /share/NAS_Share/Backup/ -name 'WeeklyBackup*.tar' -type f -mtime +60 -print -delete"
  delete_old_monthly_backups_disk: "find /share/NAS_Share/Backup/ -name 'MonthlyBackup*.tar' -type f -mtime +120 -print -delete"