shell_command:
  timelapse_webcam1: "ffmpeg -framerate 8 -pattern_type glob -i '/media/m5ccam/pictures/*.jpg' -c:v libx264 -crf 30 -pix_fmt yuv420p -y /media/m5ccam/video_`date +%d_%m_%Y_%X`.mp4 > /dev/null 2>&1 &"
  call_timelapse_script: "/config/Ffmpeg_timelapse.sh '{{output_filename}}'"
  delete_files_webcam1: 'rm -f /media/m5ccam/pictures/*.jpg'
  delete_old_backups_disk: "find /share/USBMEDIABACKUP_Share/Backup/ -name 'DailyBackup*' -type f -mtime +7 -delete"
  delete_old_weekly_backups_disk: "find /share/USBMEDIABACKUP_Share/Backup/ -name 'WeeklyBackup*.tar' -type f -mtime +60 -delete"
  delete_old_monthly_backups_disk: "find /share/USBMEDIABACKUP_Share/Backup/ -name 'MonthlyBackup*.tar' -type f -mtime +120 -delete"