# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

recorder:
  purge_keep_days: 10
  commit_interval: 10
  db_url: !secret db_url
  exclude:
    event_types:
      - call_service
      - service_registered
      - automation_triggered
      - recorder_5min_statistics_generated
      - recorder_hourly_statistics_generated
    domains:
      - assist_satellite
      - button
      - calendar
      - camera
      - conversation
      - datetime
      - event
      - image
      - lock
      - input_text
      - plant
      - scene
      - script
      - siren
      - time
      - todo
      - update
      - vacuum
      - zone
    entities:
      - sensor.known_power
      - sensor.known_energy
      - sensor.unmonitored
      - sensor.unmonitored_consumption
      - sensor.exclude_from_power_ranking
      - sensor.grid_import
      - sensor.grid_export
      - sensor.grid_export_negative
      - binary_sensor.smart_meter_mqtt_data
      - sensor.grid_consumption
      - sensor.grid_production
      - sensor.smart_meter_mqtt_grid_power
      - sensor.tibber_bridge_0100100700ff
      - sensor.energy_summary_1st_block
      - sensor.energy_summary_1st_block_2
      - sensor.appliance_used
      - sensor.id_4_remaining_charging_time
      - sensor.zoe_remaining_charging_time
      - sensor.vw_status
      - sensor.zoe_status
      - sensor.mg4_status
      - sensor.total_print_time
      - sensor.remaining_time
      - sensor.elapsed_time
      - sensor.finish_time
      - sensor.wind_direction
      - sensor.speedtest_last_run
      - sensor.solar_forecast_text_tomorrow
      - sensor.solar_forecast_text_today
      - sensor.boiler_remaining_time
      - sensor.uptime
      - sensor.local_ip
      - sensor.herd_ct_klemme_zigbee_power_a
      - sensor.herd_ct_klemme_zigbee_power_b
      - sensor.system_monitor_letzter_start
      - sensor.go_echarger_252682_nrg
      - sensor.go_echarger_270862_nrg
      - automation.publish_to_mqtt_grid_export
      - sensor.stephans_iphone_next_update
      - sensor.enyas_iphone_next_update
      - sensor.stephans_iphone_arrival_time
      - sensor.enyas_iphone_arrival_time
      - sensor.enyas_iphone_last_update
      - sensor.enyas_iphone_last_located
      - sensor.stephans_iphone_last_located
      - sensor.stephans_iphone_last_update
      - sensor.enyas_iphone_info
      - sensor.stephans_iphone_info
      - sensor.papa_to_arbeit_travel_time
      - binary_sensor.show_papa_travel_dashboard
      - sensor.forecast_text
      - sensor.remainingtototalforecast
      - automation.connectivity_ping_update
      - sensor.pool_pumpe_energy_power
      - sensor.stadt_rauenberg_vorwarnstufe
      - sensor.stadt_rauenberg_aktuelle_warnstufe
      - sensor.evs_home_and_ready_to_charge
      - sensor.issues
      - sensor.ignored_issues
      - sensor.active_issues
      - sensor.icloud3_event_log
      - sensor.icloud3_wazehist_track
      - sensor.kellervorrate_combined_filtered_items
      - sensor.kellervorrate_combined_filtered_items_hash
      - switch.153931628718174_prompt_tone
      - binary_sensor.rollo_summer_should_close
      - sensor.cudy_data_sent
      - sensor.cudy_data_received
      - sensor.cudy_router_betriebszeit
      - sensor.tasmota_newest_version
      - sensor.openbk7231t_app_newest_version
      - binary_sensor.upcoming_birthdays
      - sensor.voltage_l1
      - sensor.voltage_l2
      - sensor.voltage_l3
    entity_globs:
      - sensor.dreamebot_d10_plus_*
      - sensor.d9_max_gen_2_*
      - sensor.dwd_weather_warnings_*
      - sensor.*_rssi
      - sensor.*_signal
      - sensor.*_signal_db*
      - sensor.m2101k6g*
      - sensor.m2010j19cg*
      - sensor.24069pc21g*
      - sensor.redmi_note_8t*
      - sensor.mi_9t*
      - sensor.iphone_von_*
      - sensor.ipad_von*
      - sensor.*_firmware_version
      - sensor.*_build
      - sensor.irauen33_*
      - sensor.localhost_*
      - sensor.*_uptime*
      - sensor.*linkquality
      - sensor.everything_presence_lite_f1c0d0_*
      
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js

homeassistant:
  packages: !include_dir_named packages
  media_dirs:
    recordings: "/media/frigate"
    3dprinter: "/media/m5ccam"
    chime: "/media/sounds"
    timemachine: "/media/timemachine"
  allowlist_external_dirs:
    - "/media/"
    - "/share/NAS_Share"

go2rtc:
  url: http://192.168.2.205:1984

readme:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
