go2rtc:
  streams:
    terrasse_tapo:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.20/stream1#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.20
    ding_dong_tapo:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.21/stream1#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.21
    keller_tapo:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.22/stream1#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.22
    autos_tapo:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.23/stream1#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.23
    autos_tapo_detect:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.23/stream2#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.23
    keller_tapo_detect:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.22/stream2#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.22
    ding_dong_tapo_detect:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.21/stream2#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.21
    terrasse_tapo_detect:
      - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.20/stream2#video=copy#audio=copy#audio=aac
      - tapo://Clyde123@192.168.2.20
  webrtc:
    candidates:
      - stun:8555
  api:
    origin: '*'

mqtt:
  host: 192.168.2.205
  port: 1883
  user: mqtt
  password: mqtt
  topic_prefix: frigate

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - car

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  autos_tapo:
    ffmpeg:
      retry_interval: 60
      inputs:
        - path: rtsp://127.0.0.1:8554/autos_tapo?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/autos_tapo_detect?video=copy&audio=aac
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - yell
        - glass
        - smash
        - speech
        - fire_alarm
        - smoke_detector
      filters:
        speech:
          threshold: 0.6
        glass:
          threshold: 0.5
        fire_alarm:
          threshold: 0.5
        smoke_detector:
          threshold: 0.5
    detect:
      enabled: true
      fps: 10
    onvif:
      host: 192.168.2.23
      port: 2020
      user: tpadmin
      password: tpadmin
    motion:
      mask: 0.362,0.05,0,0.05,0,0,0.361,0
    zones:
      Bewegung:
        coordinates: 
          0,1,-0.001,0.057,0.364,0.053,0.364,0,0.799,0,0.923,0.227,0.997,0.609,1,0.876,0.919,1
        loitering_time: 0
        inertia: 3
    objects:
      filters:
        cat:
          mask: 0,0.058,0.079,0.065,0.156,0.988,0,1
  keller_tapo:
    ffmpeg:
      retry_interval: 60
      inputs:
        - path: rtsp://127.0.0.1:8554/keller_tapo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/keller_tapo_detect?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - yell
        - glass
        - smash
        - speech
        - fire_alarm
        - smoke_detector
      filters:
        speech:
          threshold: 0.6
        glass:
          threshold: 0.5
        fire_alarm:
          threshold: 0.5
        smoke_detector:
          threshold: 0.5
    detect:
      enabled: true
      fps: 10
    onvif:
      host: 192.168.2.22
      port: 2020
      user: tpadmin
      password: tpadmin
    motion:
      mask: 0.36,0.048,0,0.05,0,0,0.359,0
    zones:
      Bewegung:
        coordinates: 
          0.182,0.167,0.178,0.241,0.248,0.32,0.246,0.361,0.275,0.377,0.281,0.436,0.314,0.415,0.411,0.365,0.501,0.307,0.62,0.224,0.666,0.275,0.704,0.244,0.723,0.094,0.775,0.1,0.804,0.105,0.837,0.082,0.882,0.09,0.89,0.008,0.995,0.005,0.998,0.256,1,0.493,0.77,0.656,0.658,0.787,0.458,0.779,0.232,0.777,0.201,0.717,0.001,0.864,-0.001,0.261,0,0.111,0.181,0.115
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - cat
  ding_dong_tapo:
    ffmpeg:
      retry_interval: 60
      inputs:
        - path: rtsp://127.0.0.1:8554/ding_dong_tapo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/ding_dong_tapo_detect?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - yell
        - glass
        - smash
        - speech
        - fire_alarm
        - smoke_detector
      filters:
        speech:
          threshold: 0.6
        glass:
          threshold: 0.5
        fire_alarm:
          threshold: 0.5
        smoke_detector:
          threshold: 0.5
    detect:
      enabled: true
      fps: 10
    onvif:
      host: 192.168.2.21
      port: 2020
      user: tpadmin
      password: tpadmin
    motion:
      mask: 0.362,0.05,0,0.05,0,0,0.361,0
    zones:
      Bewegung:
        coordinates: 
          0,1,0,0.92,0,0.213,0.047,0.057,0.092,0.061,0.111,0.229,0.211,0.46,0.32,0.428,0.451,0.451,0.539,0.345,0.581,0.211,0.547,0,0.726,0,0.695,0.22,0.718,0.364,0.745,0.502,0.815,0.648,0.714,0.635,0.695,0.705,0.697,0.783,0.722,0.866,0.737,0.929,0.761,0.947,0.77,0.961,0.8,0.959,0.815,0.954,0.833,0.954,0.863,0.934,0.87,0.917,0.881,0.887,0.893,0.862,0.909,0.843,0.949,0.841,0.976,0.839,0.998,0.833,1,1,0.041,1
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - cat
    objects:
      filters:
        person: {}
  terrasse_tapo:
    ffmpeg:
      retry_interval: 60
      inputs:
        - path: rtsp://127.0.0.1:8554/terrasse_tapo?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/terrasse_tapo_detect?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - yell
        - glass
        - smash
        - speech
        - fire_alarm
        - smoke_detector
      filters:
        speech:
          threshold: 0.6
        glass:
          threshold: 0.5
        fire_alarm:
          threshold: 0.5
        smoke_detector:
          threshold: 0.5
    detect:
      enabled: true
      fps: 10
    onvif:
      host: 192.168.2.20
      port: 2020
      user: tpadmin
      password: tpadmin
    motion:
      mask: 0.362,0.05,0,0.05,0,0,0.361,0
    zones:
      Bewegung:
        coordinates: 
          0,1,0,0.054,0.363,0.053,0.407,0.113,0.467,0.116,0.476,0.026,0.653,0.157,0.695,0,0.833,0.003,0.948,0.004,0.945,0.034,0.998,0.132,0.999,0.385,0.999,0.997
        loitering_time: 0
        objects:
          - cat
          - person
        inertia: 3
ffmpeg:
  hwaccel_args: preset-vaapi #or,preset-vaapi depending on your CPU use preset-intel-qsv-h264 / preset-intel-qsv-h265
  output_args:
    record: preset-record-generic-audio-copy
version: 0.15-1
