streams:
  # cloud password without username
  camera1: onvif://tpadmin:tpadmin@192.168.2.20:2020
  camera2: onvif://tpadmin:tpadmin@192.168.2.21:2020
  camera3: onvif://tpadmin:tpadmin@192.168.2.22:2020
  camera4: onvif://tpadmin:tpadmin@192.168.2.23:2020
  camera5: onvif://tpadmin:tpadmin@192.168.2.24:2020