streams:
  terrasse_tapo:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.20/stream1#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.20
  ding_dong_tapo:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.21/stream1#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.21
  keller_tapo:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.22/stream1#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.22
  autos_tapo:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.23/stream1#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.23
  autos_tapo_detect:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.23/stream2#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.23
  keller_tapo_detect:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.22/stream2#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.22
  ding_dong_tapo_detect:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.21/stream2#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.21
  terrasse_tapo_detect:
    - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.20/stream2#video=copy#audio=copy#audio=aac
    - tapo://Clyde123@192.168.2.20
  #ankermake_m5c_tapo:
  #  - ffmpeg:rtsp://tpadmin:tpadmin@192.168.2.24/stream2#video=copy#audio=copy#audio=aac
  #  - tapo://Clyde123@192.168.2.24
  frigate_01K74QMA06T1R83GS2WG5EF4ZV%3Acamera%3Aautos_tapo:
    - rtsp://ccab4aaf-frigate-fa:8554/autos_tapo
    - ffmpeg:frigate_01K74QMA06T1R83GS2WG5EF4ZV%3Acamera%3Aautos_tapo#audio=opus#query=log_level=debug
