
# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
db_url: ""

tibber_pulse_url: ""

tibber_bridge_url: ""

gas_token: ""
tibber_token: ""

github_api_authorization: ""