answer_after: 0
webhook_to_call:
    call_established: sip_call_established
    entered_menu: sip_entered_menu
    dtmf_digit: sip_dtmf_digit
    call_disconnected: sip_call_disconnected
action:
    domain: light
    service: turn_off
    entity_id: light.orangina_local
menu:
    id: main
    message: "Willkommen. Bitte geben Sie Ihren Zugangscode ein."
    choices_are_pin: true
    timeout: 15
    post_action: repeat_message
    choices:
        '1234':
            id: owner
            message: "Code akzeptiert. Licht wird ausgeschaltet. Auf Wiedersehen."
            post_action: hangup 
        '5432':
            id: maintenance
            message: "Ihr Zutritt wurde protokolliert."
            post_action: hangup
        'default':
            id: wrong_code
            message: "Falscher Code. Bitte versuchen Sie es erneut."
            post_action: return
        'timeout':
            id: timeout
            message: "Zeitüberschreitung. Auf Wiedersehen."
            post_action: hangup
            