esphome:
  name: esp32-c3-mini--bett-nachtlicht
  friendly_name: esp32 c3 mini - bett nachtlicht
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
   level: DEBUG
   initial_level: INFO

select:
  - platform: logger
    id: logger_select
    name: Logger Level

# Enable Home Assistant API
api:
  encryption:
    key: "uB2eF4GroWy1rwSf5HJ18F6+9+k5i1F6RPbIbJPRIQY="

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 192.168.2.1
    static_ip: 192.168.2.35
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Mini--Bett-Nachtlicht"
    password: !secret ap_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

output:
  - platform: ledc
    pin: GPIO4
    frequency: 20000Hz
    id: light_one

light:
  - platform: status_led
    name: Status LED
    pin: 
      number: GPIO8
      ignore_strapping_warning: true
      inverted: true

  - platform: monochromatic
    name: Bettlicht
    output: light_one
    id: night_light
    on_turn_on: 
      then:
        - delay: !lambda return id(reentered_bed).state * 1000;
        - if:
            condition:
              - binary_sensor.is_on: mb_o
            then:
              - light.turn_off: night_light

script:
  - id: was_in_bed_script
    mode: restart
    then:
      - if:
          condition: 
            binary_sensor.is_on: mb_o
          then:
            - delay: !lambda return id(consider_in_bed).state * 60 * 1000;
            - if:
                condition: 
                  binary_sensor.is_on: mb_o
                then:
                  - switch.turn_on: was_in_bed
                
  - id: left_bed_script
    mode: restart
    then:
      - if:
          condition:
            - binary_sensor.is_off: mb_o
          then:
            - delay: !lambda return id(consider_out_of_bed).state * 60 * 1000;
            - if:
                condition: 
                  - binary_sensor.is_off: mb_o
                then:
                  - switch.turn_off: was_in_bed              

switch:
  - platform: template
    name: Was In Bed
    id: was_in_bed
    optimistic: True
    icon: mdi:bed
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: homeassistant
    entity_id: switch.bett_power_strip_l5
    id: phone_charge
    internal: True

button:
  - platform: restart
    name: Restart

binary_sensor:
  - platform: status
    name: Status

  - platform: template
    name: Master Bed Occupied
    id: mb_o
    lambda: |-
      if (id(master_bed_sensor).state > id(trigger_level).state) {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - light.turn_off: night_light
        - switch.turn_on: phone_charge
        - script.execute: was_in_bed_script
    on_release: 
      then:
        - if:
            condition:
              - switch.is_on: was_in_bed
            then:
              - light.turn_on:
                  id: night_light
                  brightness: !lambda return id(night_brightness).state/ 100.0;
        - script.execute: left_bed_script

number:
  - platform: template
    name: Master Bed Trigger Level
    id: trigger_level
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 3.0
    step: 0.05
    icon: mdi:arrow-collapse-down
    mode: BOX
    unit_of_measurement: V
    entity_category: diagnostic

  - platform: template
    id: consider_in_bed
    name: Time to consider in Bed
    min_value: 0
    max_value: 60
    step: 0.5
    initial_value: 3
    optimistic: True
    restore_value: True
    unit_of_measurement: min
    mode: BOX
    entity_category: diagnostic
  
  - platform: template
    id: consider_out_of_bed
    name: Time to consider out of Bed
    min_value: 0
    max_value: 60
    step: 0.5
    initial_value: 15
    optimistic: True
    restore_value: True
    mode: BOX
    unit_of_measurement: min
    entity_category: diagnostic
  
  - platform: template
    id: reentered_bed
    name: Time to Re-Enter Bed
    min_value: 0
    max_value: 60
    step: 1
    initial_value: 5
    optimistic: True
    restore_value: True
    mode: BOX
    unit_of_measurement: s
    entity_category: diagnostic

  - platform: template
    id: night_brightness
    name: Night Light Brightness
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 20
    restore_value: True
    optimistic: True
    mode: BOX
    unit_of_measurement: '%'
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    accuracy_decimals: 1
    name: Wifi Signal
    update_interval: 5s
    filters: 
      - or: 
        - delta: 5%
        - throttle: 120s
  
  - platform: uptime
    name: Uptime
    update_interval: 3s
    device_class: duration
    accuracy_decimals: 1
    state_class: total
    unit_of_measurement: min
    filters:
      - lambda: !lambda return x / 60;
      - or:
        - delta: 5%
        - throttle: 120s

  - platform: adc
    internal: False
    pin: GPIO1
    samples: 5
    attenuation: 12db
    sampling_mode: max
    name: Master Bed Sensor
    id: master_bed_sensor
    icon: mdi:bed
    update_interval: 250ms
    state_class: measurement
    device_class: voltage
    unit_of_measurement: V
    filters:
      - or:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 4
        - throttle_average: 180s
      - clamp:
          max_value: 1.5
          min_value: 0.1