substitutions:
  name: esp32-c3-mini--dht22-sensor
  friendly_name: ESP32 C3 mini - DHT22 Compact

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  on_boot: 
    then:
      - button.press: status_led_btn
      - deep_sleep.prevent: deep
      - if: 
          condition:
            - switch.is_off: disable_deepsleep
          then:
            - delay: 60s
            - if: 
                condition:
                  - switch.is_off: disable_deepsleep
                then:
                  - deep_sleep.allow: deep
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  initial_level: INFO

select:
  - platform: logger
    name: Logger Level 
    id: logger_select

# Enable Home Assistant API
api:
  encryption:
    key: "AXfsQvDFfThiaps/L9S07/t/2DHDBJ7U04cOm4pHEWY="

ota:
  - platform: esphome
    password: !secret ota_password
    on_state_change: 
      then:
        - deep_sleep.prevent: deep

deep_sleep:
  id: deep
  sleep_duration: 
    minutes: 4.5
  run_duration: 
    seconds: 30
      
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 10
      manual_ip: 
        gateway: 192.168.2.1
        dns1: 192.168.2.1
        static_ip: 192.168.2.45
        subnet: 255.255.255.0
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password
      priority: 8
      manual_ip: 
        gateway: 192.168.2.1
        dns1: 192.168.2.1
        static_ip: 192.168.2.45
        subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "DHT22 Compact Fallback Hotspot"
    password: !secret ap_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

output:
  - platform: gpio
    pin: 
      number: GPIO8
      ignore_strapping_warning: True
      inverted: True
    id: led_blue

switch:
  - platform: template
    assumed_state: False
    id: disable_deepsleep
    restore_mode: RESTORE_DEFAULT_OFF
    name: Disable Deepsleep
    optimistic: True
    on_turn_on: 
      then:
        - deep_sleep.prevent: deep
    on_turn_off: 
      then:
        - deep_sleep.allow: deep

button:
  - platform: output
    output: led_blue
    name: Status LED
    id: status_led_btn
    duration: 
      milliseconds: 125

  - platform: restart
    name: Restart

binary_sensor:
  - platform: status
    name: Status
    id: status_bin
    on_state: 
      then:
        - if: 
            condition: 
              - binary_sensor.is_on: status_bin
            then: 
              - button.press: status_led_btn

sensor:  
  - platform: dht
    update_interval: 5s
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    model: DHT22
    temperature: 
      accuracy_decimals: 2
      name: Temperature
      id: temperature
      on_value: 
        then:
          - button.press: status_led_btn
      filters:
        - or:
          - throttle: 60s
          - delta: 3%
    humidity: 
      accuracy_decimals: 2
      name: Humidity
      id: humidity
      filters:
        - or:
          - throttle: 60s
          - delta: 3%

  - platform: uptime
    name: Uptime
    update_interval: 5s
    filters:
      - or:
        - throttle: 60s
        - delta: 5%

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"
    filters: 
        - or: 
          - throttle: 120s
          - delta: 2%