esphome:
  name: esp32-c3-mini--terra
  friendly_name: esp32 c3 mini - Terra
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      # - lambda: !lambda 'id(esphome_ota).set_auth_password("6914Sim@duncanz");'
      - deep_sleep.prevent: deep
      - if: 
          condition:
            - switch.is_off: disable_deepsleep
          then:
            - delay: 60s
            - deep_sleep.allow: deep

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERBOSE
  initial_level: INFO

select:
  - platform: logger
    id: logger_select
    name: Logger Level

# Enable Home Assistant API
api:
  encryption:
    key: "gXcuyN/vG98qdO5OwHwf6YEVCSU7oO7qkdoZVqjSleM="

ota:
  - platform: esphome
    id: esphome_ota 
    password: !secret ota_password
    on_state_change:
      then:
        - deep_sleep.prevent: deep

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    gateway: 192.168.2.1
    static_ip: 192.168.2.34
    subnet: 255.255.255.0
    dns1: 192.168.2.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Mini--Terra"
    password: !secret ap_password

captive_portal:

deep_sleep:
  run_duration: 30s
  sleep_duration: 4.5min
  id: deep

output:
  - platform: gpio
    id: led_status
    pin:
      number: GPIO8
      ignore_strapping_warning: true
      inverted: true

light:
  - platform: binary
    output: led_status
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    restore_mode: ALWAYS_OFF

i2c:
  sda: 20
  scl: 21
  scan: False
  id: bus_a

button:
  - platform: restart
    name: "Terra Sensor Restart"

binary_sensor:
  - platform: status
    name: "Terra Sensor Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

one_wire:
  - platform: gpio
    pin: 10

switch:
  - platform: template
    assumed_state: False
    id: disable_deepsleep
    restore_mode: RESTORE_DEFAULT_OFF
    name: Disable Deepsleep
    optimistic: True
    on_turn_on: 
      then:
        - deep_sleep.prevent: deep
    on_turn_off: 
      then:
        - deep_sleep.allow: deep

sensor:
  # - platform: absolute_humidity
  #   name: Right Absolute Humidity
  #   id: right_absolute_humidity
  #   temperature: right_temperature
  #   humidity: right_humidity
  #   internal: True

  # - platform: absolute_humidity
  #   name: Middle Absolute Humidity
  #   id: middle_absolute_humidity
  #   temperature: middle_temperature
  #   humidity: middle_humidity
  #   internal: True

  # - platform: absolute_humidity
  #   name: Left Absolute Humidity
  #   id: left_absolute_humidity
  #   temperature: left_temperature
  #   humidity: left_humidity
  #   internal: True
    
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 1s
    filters: 
       - or:
          - delta: 3%
          - throttle: 30s
    
  - platform: dallas_temp
    resolution: 12
    address: 0x070120632f4e4e28
    name: "Duncan Room Temperature"
    accuracy_decimals: 2
    update_interval: 5s
    filters: 
        - or:
          - throttle: 30s
          - delta: 3%

  - platform: dht
    model: DHT22
    pin: 0
    temperature:
      name: "Right Temperature"
      id: right_temperature
      internal: True
      filters: 
        - or:
          - throttle: 30s
          - delta: 2%
    humidity:
      name: "Right Humidity"
      id: right_humidity
      internal: True
      filters:
        - or:
          - throttle: 30s
          - delta: 2%
    update_interval: 1s
  - platform: dht
    model: DHT22_TYPE2
    pin: 1
    temperature:
      name: "Middle Temperature"
      id: middle_temperature
      internal: True
      filters: 
        - or:
          - throttle: 30s
          - delta: 2%
    humidity:
      name: "Middle Humidity"
      id: middle_humidity
      internal: True
      filters: 
        - or:
          - throttle: 30s
          - delta: 2%
    update_interval: 1s
  - platform: dht
    model: DHT22
    pin: 3
    temperature:
      name: "Left Temperature"
      id: left_temperature
      internal: True
      filters: 
        - or:
          - throttle: 30s
          - delta: 2%
    humidity:
      name: "Left Humidity"
      id: left_humidity
      internal: True
      filters: 
        - or:
          - throttle: 30s
          - delta: 2%
    update_interval: 1s

  - platform: template
    id: "terra_temperature_average"    
    name: "Terrarium Temperature Average"
    unit_of_measurement: °C
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
          float sum = 0;
          uint16_t cnt = 0;
          if (!std::isnan(id(left_temperature).state)) {
            sum += id(left_temperature).state;
            cnt += 1;
          }
          if (!std::isnan(id(middle_temperature).state)) {
            sum += id(middle_temperature).state;
            cnt += 1;
          }
          if (!std::isnan(id(right_temperature).state)) {
            sum += id(right_temperature).state;
            cnt +=1;
          }
          if (cnt == 0) {
            return NAN;
          } else {
            return (sum / cnt);
          }
    filters: 
      - or:
        - delta: 2%
        - throttle: 30s

  - platform: template
    id: "terra_humidity_average"
    name: "Terrarium Humidity Average"
    unit_of_measurement: '%'
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      float sum = 0;
      uint16_t cnt = 0;
      if (!std::isnan (id(left_humidity).state)) {
        sum += id(left_humidity).state;
        cnt += 1;
      }
      if (!std::isnan (id(middle_humidity).state)) {
        sum += id(middle_humidity).state;
        cnt += 1;
      }
      if (!std::isnan (id(right_humidity).state)) {
        sum += id(right_humidity).state;
        cnt +=1;
      }
      if (cnt == 0) {
        return NAN;
      } else {
        return (sum / cnt);
      }
    filters: 
      - or:
        - delta: 2%
        - throttle: 30s
            
  # - platform: template
  #   id: "terra_absolute_humidity_average"
  #   name: "Terrarium Absolute Humidity Average"
  #   unit_of_measurement: 'g/m³'
  #   accuracy_decimals: 2
  #   update_interval: 5s
  #   lambda: |-

  #     float sum = 0;
  #     uint16_t cnt = 0;
  #     if (!std::isnan (id(left_absolute_humidity).state)) {
  #       sum += id(left_absolute_humidity).state;
  #       cnt += 1;
  #     }
  #     if (!std::isnan (id(middle_absolute_humidity).state)) {
  #       sum += id(middle_absolute_humidity).state;
  #       cnt += 1;
  #     }
  #     if (!std::isnan (id(right_absolute_humidity).state)) {
  #       sum += id(right_absolute_humidity).state;
  #       cnt +=1;
  #     }
  #     if (cnt == 0) {
  #       return NAN;
  #     } else {
  #       return (sum / cnt);
  #     }
  #   filters: 
  #     - or:
  #       - delta: 2%
  #       - throttle: 30s
            
  - platform: uptime
    name: Uptime
    update_interval: 5s
    disabled_by_default: True
    filters: 
      - or:
        - delta: 5%
        - throttle: 120s
    
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"
    filters: 
      - or:
        - delta: 5%
        - throttle: 120s