# Board: M5Stack Atom Echo (M5Stack)
# Definition: definitions/boards/m5stack-atom-echo/manifest.yaml

esphome:
  name: m5stack-atom-echo-31b31c
  friendly_name: M5Stack Atom Echo

esp32:
  variant: esp32
  flash_size: 4MB
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: InsPzpQ6OesB3txPXXV3yBB7D76HVWFdua9+mU+fntg=

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: M5Stack Atom Ec Fallback Hotspot
    password: !secret ap_password

captive_portal: