substitutions:
  name: m5stack-atom-echo-31b31c
  friendly_name: M5Stack Atom Echo 31b31c
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: InsPzpQ6OesB3txPXXV3yBB7D76HVWFdua9+mU+fntg=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
