blueprint:
  name: "To-do Search: Hash"
  domain: template
  input:
    source_sensor:
      name: Source Items Sensor
      selector:
        entity:
          domain: sensor

variables:
  source: !input source_sensor

trigger:
  - platform: state
    entity_id: !input source_sensor
  - platform: state
    entity_id: !input source_sensor
    attribute: filtered_items

sensor:
  - name: "Items Hash"
    unique_id: "hash_sensor_{{ source | replace('.', '_') }}"
    state: >
      {% set f_items = state_attr(source, 'filtered_items') | default([]) | to_json %}
      {% set s_map = state_attr(source, 'source_map') | default({}) | to_json %}
      {{ (f_items ~ s_map) | md5 }}