title: "Hallo {{ user_name }}"
subtitle: "Reif für die 550"
#sidebar_background: center / cover no-repeat fixed url('https://cdn.jsdelivr.net/gh/basnijholt/lovelace-ios-themes@a37376d918fcfe4785be99910dc9a7200ac37da9/themes/homekit-bg-blue-red.jpg')
sidebar_editable: False
order:
  - item: /lovelace
    order: 0
    match: href
  - item: /fire-hd-8
    match: href
    order: 2
  - item: /energy
    icon: mdi:home-lightning-bolt-outline
    match: href
    order: 3
  - item: /test-sankey
    match: href
    icon: mdi:chart-sankey
    order: 4
    info: |
        Haus: {{states('sensor.home_power', with_unit=True)}} | Netz: {{states('sensor.grid_power', with_unit=True)}}
  - item: /dashboard-scheduler
    match: href
    order: 5
  - item: /media-browser
    match: href
    order: 6
    info: |
        Size: {{ states('sensor.media_folder_size', with_unit=True) }}
  - item: /dashboard-enya
    match: href
    hide: true
  
  - item: /calendar
    match: href
    hide: true
  - item: /todo
    match: href
    hide: true
  - item: /logbook
    match: href
    hide: true
  - item: /map
    match: href
    hide: true
  - item: /history
    match: href
    hide: true


exceptions:
  - user:
    - Duncan
    - Stephan
    extend_from: base
    order:
      - item: /dashboard-analysis
        order: 1
        match: href
        info: |
          {% set rows = states('sensor.maria_db_rows') | int(0)%} {{ ((states('sensor.maria_db_size') | float(0)) * 1000000) | filesizeformat() }}  {{ ' / ' +  (rows/ 1000000)|round(1)|string + ' Mio Rows' }}
      - item: /45df7312_zigbee2mqtt
        match: href
        name: Z2M
        order: 7
        bottom: true
      - item: /ccab4aaf_frigate-fa
        match: href
        order: 8
        bottom: true
        hide: false
      - item: /core_configurator
        bottom: true
        match: href
        order: 9
      - item: /hacs
        match: href
        order: 10
        bottom: true
        notification: |
          [[[
            const outdatedHacsEntities = Object.values(entities.update).filter(
              (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
            );
            return outdatedHacsEntities.length || '';
          ]]]
      - item: Integrationen
        icon: mdi:puzzle
        order: 11
        bottom: true
        new_item: true
        href: "/config/integrations"
        info: |
          {{states('sensor.devices')}} Geräte | {{states('sensor.entities')}} Entitäten
      - item: Automationen
        icon: mdi:robot
        order: 12
        bottom: true
        new_item: true
        href: "/config/automation"
        info: |
            {{ states.automation | selectattr('state', 'eq', 'off') | list | count }} inaktive |  {{ states.automation | selectattr('state', 'eq', 'on') | list | count }} aktive
      - new_item: true
        item: 'info'
        name: 'Info ({{ state_attr("update.home_assistant_supervisor_update", "latest_version") }})'
        info: 'OS {{ state_attr("update.home_assistant_operating_system_update", "latest_version") }}'
        href: '/hassio/system/info'
        icon: 'mdi:information-outline'
        bottom: true
        order: 13
      - item: /developer-tools
        icon: mdi:tools
        match: href
        order: 14
        bottom: true
      - item: /config
        match: href
        order: 15
        bottom: true

  - user:  
    - Katalin
    - Enya
    extend_from: base
    order:
      - item: /config
        hide: false
        match: href
      - item: /developer-tools
        match: href
        hide: true
      - item: /45df7312_zigbee2mqtt
        match: href
        hide: true
      - item: /core_configurator
        match: href
        hide: true
      - item: /hacs
        match: href
        hide: true
      - item: /dashboard-analysis
        match: href
        hide: true